/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2ssijmpuSD4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function ngof() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <MountainIcon className="h-8 w-8" />
          <span className="text-xl font-bold">Acme NGO</span>
        </div>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Projects
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            CSR
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="outline" className="md:hidden">
          <MenuIcon className="h-6 w-6" />
        </Button>
      </header>
      <main className="flex-1">
        <section className="bg-primary py-12 md:py-24 lg:py-32 text-primary-foreground">
          <div className="container px-4 md:px-6 grid gap-6 md:grid-cols-2 items-center">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                Empowering Communities, Transforming Lives
              </h1>
              <p className="text-lg md:text-xl">
                At Acme NGO, we are dedicated to making a lasting impact on the communities we serve. Join us in our
                mission to create a better world.
              </p>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-secondary px-8 text-sm font-medium text-secondary-foreground shadow transition-colors hover:bg-secondary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Explore Projects
              </Link>
            </div>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Hero"
              className="mx-auto aspect-video rounded-lg object-cover"
            />
          </div>
        </section>
        <section id="projects" className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Projects</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Explore the impact we're making in communities around the world.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card className="border-0 shadow-lg">
                <CardContent className="p-0">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="Project"
                    className="aspect-video object-cover rounded-t-lg"
                  />
                </CardContent>
                <CardHeader className="px-6 py-4">
                  <h3 className="text-xl font-bold">Clean Water Initiative</h3>
                  <p className="text-muted-foreground mt-2">
                    Providing access to clean water for underserved communities.
                  </p>
                </CardHeader>
                <CardFooter className="px-6 pb-6">
                  <Button>Donate</Button>
                </CardFooter>
              </Card>
              <Card className="border-0 shadow-lg">
                <CardContent className="p-0">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="Project"
                    className="aspect-video object-cover rounded-t-lg"
                  />
                </CardContent>
                <CardHeader className="px-6 py-4">
                  <h3 className="text-xl font-bold">Education for All</h3>
                  <p className="text-muted-foreground mt-2">
                    Ensuring access to quality education for children in need.
                  </p>
                </CardHeader>
                <CardFooter className="px-6 pb-6">
                  <Button>Donate</Button>
                </CardFooter>
              </Card>
              <Card className="border-0 shadow-lg">
                <CardContent className="p-0">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="Project"
                    className="aspect-video object-cover rounded-t-lg"
                  />
                </CardContent>
                <CardHeader className="px-6 py-4">
                  <h3 className="text-xl font-bold">Sustainable Agriculture</h3>
                  <p className="text-muted-foreground mt-2">
                    Empowering farmers to adopt eco-friendly farming practices.
                  </p>
                </CardHeader>
                <CardFooter className="px-6 pb-6">
                  <Button>Donate</Button>
                </CardFooter>
              </Card>
            </div>
            <div className="mx-auto max-w-md">
              <form className="grid gap-4">
                <Input type="text" placeholder="Project Name" className="w-full" />
                <Textarea placeholder="Project Description" className="w-full" rows={4} />
                <Input type="text" placeholder="Project Location" className="w-full" />
                <Input type="number" placeholder="Funding Needed" className="w-full" />
                <Button type="submit">Submit Project</Button>
              </form>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 grid gap-6 md:grid-cols-2 items-center">
            <div>
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="CSR"
                className="mx-auto aspect-video rounded-lg object-cover"
              />
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Corporate Social Responsibility
              </h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Partner with us to make a lasting impact on the communities we serve. Discover the benefits of CSR
                funding and how your company can get involved.
              </p>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
          </div>
        </section>
        <section id="csr" className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">CSR Funding Opportunities</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Discover how your company can make a difference.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card className="border-0 shadow-lg">
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold">Tax Benefits</h3>
                    <p className="text-muted-foreground">
                      Enjoy tax deductions and incentives for your CSR contributions.
                    </p>
                  </div>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-lg">
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold">Brand Visibility</h3>
                    <p className="text-muted-foreground">
                      Showcase your company's commitment to social responsibility and gain positive brand recognition.
                    </p>
                  </div>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-lg">
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold">Employee Engagement</h3>
                    <p className="text-muted-foreground">
                      Boost employee morale and retention by involving them in your CSR initiatives.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="mx-auto max-w-md">
              <form className="grid gap-4">
                <Input type="text" placeholder="Company Name" className="w-full" />
                <Input type="email" placeholder="Email Address" className="w-full" />
                <Textarea placeholder="Message" className="w-full" rows={4} />
                <Button type="submit">Submit Interest</Button>
              </form>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Have a question or want to learn more? Contact us today.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Address</h3>
                <p className="text-muted-foreground">123 Main Street, Anytown USA</p>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Phone</h3>
                <p className="text-muted-foreground">+1 (555) 123-4567</p>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Email</h3>
                <p className="text-muted-foreground">info@acmengo.org</p>
              </div>
            </div>
            <div className="mx-auto max-w-md">
              <form className="grid gap-4">
                <Input type="text" placeholder="Name" className="w-full" />
                <Input type="email" placeholder="Email Address" className="w-full" />
                <Textarea placeholder="Message" className="w-full" rows={4} />
                <Button type="submit">Submit</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 px-4 md:px-6 text-muted-foreground">
        <div className="container flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">&copy; 2024 Acme NGO</p>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function MenuIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
